import Header from '@/components/layout/Header'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'

const geist = Geist({
    variable: '--font-rubik',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang='en'
            className='light'>
            <body
                className={cn(
                    geist.variable,
                    geist.className,
                    'antialiased flex flex-col h-screen'
                )}>
                <Header />
                <main className='flex-1 bg-gray-100'>{children}</main>
            </body>
        </html>
    )
}
