"""modified User Session model with nullable fields

Revision ID: 07144aee96ab
Revises: 4946ad7067cb
Create Date: 2025-10-31 12:19:41.147817

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07144aee96ab"
down_revision: Union[str, Sequence[str], None] = "4946ad7067cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_sessions",
        "session_token",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        nullable=True,
        existing_comment="Cookie-based session token for authentication.",
    )
    op.alter_column(
        "user_sessions",
        "fingerprint_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        existing_comment="Hash of browser/device fingerprint for session tracking.",
    )
    op.alter_column(
        "user_sessions",
        "ip_address",
        existing_type=sa.VARCHAR(length=45),
        nullable=True,
        existing_comment="IP address of the user's device.",
    )
    op.alter_column(
        "user_sessions",
        "user_agent",
        existing_type=sa.VARCHAR(length=500),
        nullable=True,
        existing_comment="User agent string from the browser.",
    )
    op.alter_column(
        "user_sessions",
        "browser",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="Browser name and version.",
    )
    op.alter_column(
        "user_sessions",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="Timezone of the user's location.",
    )
    op.alter_column(
        "user_sessions",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_comment="Language preference of the user.",
    )
    op.drop_constraint(op.f("user_sessions_user_id_fkey"), "user_sessions", type_="foreignkey")
    op.create_foreign_key(
        None,
        "user_sessions",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_sessions", schema="public", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_sessions_user_id_fkey"),
        "user_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "user_sessions",
        "language",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
        existing_comment="Language preference of the user.",
    )
    op.alter_column(
        "user_sessions",
        "timezone",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="Timezone of the user's location.",
    )
    op.alter_column(
        "user_sessions",
        "browser",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="Browser name and version.",
    )
    op.alter_column(
        "user_sessions",
        "user_agent",
        existing_type=sa.VARCHAR(length=500),
        nullable=False,
        existing_comment="User agent string from the browser.",
    )
    op.alter_column(
        "user_sessions",
        "ip_address",
        existing_type=sa.VARCHAR(length=45),
        nullable=False,
        existing_comment="IP address of the user's device.",
    )
    op.alter_column(
        "user_sessions",
        "fingerprint_hash",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        existing_comment="Hash of browser/device fingerprint for session tracking.",
    )
    # ### end Alembic commands ###
