"""modified null constraints of session

Revision ID: 1afbd466acff
Revises: 07144aee96ab
Create Date: 2025-10-31 12:27:12.180388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1afbd466acff"
down_revision: Union[str, Sequence[str], None] = "07144aee96ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_sessions",
        "session_token",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False,
        existing_comment="Cookie-based session token for authentication.",
    )
    op.alter_column(
        "user_sessions",
        "os",
        existing_type=sa.VARCHAR(length=100),
        nullable=True,
        existing_comment="Operating system of the user's device.",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_sessions",
        "os",
        existing_type=sa.VARCHAR(length=100),
        nullable=False,
        existing_comment="Operating system of the user's device.",
    )
    op.alter_column(
        "user_sessions",
        "session_token",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True,
        existing_comment="Cookie-based session token for authentication.",
    )
    # ### end Alembic commands ###
