"""added user and session models

Revision ID: 4946ad7067cb
Revises: 
Create Date: 2025-10-30 19:56:08.805148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4946ad7067cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user.'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='Unique username, optional.'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='Full name of the user, optional.'),
    sa.Column('email', sa.String(length=100), nullable=False, comment="User's email address (unique but optional)."),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Hashed password for authentication.'),
    sa.Column('role', sa.Enum('ADMIN', 'ANONYMOUS', 'USER', name='userrole'), nullable=False, comment='User role (e.g., Admin, Anonymous, User).'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the user account is active.'),
    sa.Column('is_blocked', sa.Boolean(), nullable=False, comment='Indicates if the user is blocked from logging in.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the user was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the user was last updated.'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_users_email'), 'users', ['email'], unique=True, schema='public')
    op.create_index(op.f('ix_public_users_name'), 'users', ['name'], unique=False, schema='public')
    op.create_index(op.f('ix_public_users_username'), 'users', ['username'], unique=False, schema='public')
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user session.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID of the user who owns the session (optional).'),
    sa.Column('session_token', sa.String(length=255), nullable=False, comment='Cookie-based session token for authentication.'),
    sa.Column('fingerprint_hash', sa.String(length=255), nullable=False, comment='Hash of browser/device fingerprint for session tracking.'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment="IP address of the user's device."),
    sa.Column('user_agent', sa.String(length=500), nullable=False, comment='User agent string from the browser.'),
    sa.Column('browser', sa.String(length=100), nullable=False, comment='Browser name and version.'),
    sa.Column('os', sa.String(length=100), nullable=False, comment="Operating system of the user's device."),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='Type of device (desktop, mobile, tablet).'),
    sa.Column('device_vendor', sa.String(length=100), nullable=True, comment='Manufacturer/vendor of the device (e.g., Apple, Samsung, Dell).'),
    sa.Column('device_model', sa.String(length=100), nullable=True, comment='Specific model name of the device (e.g., iPhone 16, Galaxy S24, XPS 13).'),
    sa.Column('screen_resolution', sa.String(length=20), nullable=True, comment='Screen resolution of the device.'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment="Timezone of the user's location."),
    sa.Column('language', sa.String(length=10), nullable=False, comment='Language preference of the user.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the session was created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when the session was last updated.'),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the last activity in this session.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the session is currently active.'),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_sessions_fingerprint_hash'), 'user_sessions', ['fingerprint_hash'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=False, schema='public')
    op.create_index(op.f('ix_public_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_sessions_user_id'), table_name='user_sessions', schema='public')
    op.drop_index(op.f('ix_public_user_sessions_session_token'), table_name='user_sessions', schema='public')
    op.drop_index(op.f('ix_public_user_sessions_fingerprint_hash'), table_name='user_sessions', schema='public')
    op.drop_table('user_sessions', schema='public')
    op.drop_index(op.f('ix_public_users_username'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_name'), table_name='users', schema='public')
    op.drop_index(op.f('ix_public_users_email'), table_name='users', schema='public')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
