"""added file and workflow models

Revision ID: 69f53731eb20
Revises: 1afbd466acff
Create Date: 2025-10-31 15:28:21.484653

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69f53731eb20"
down_revision: Union[str, Sequence[str], None] = "1afbd466acff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique identifier for the workflow."),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="ID of the user who owns this workflow."
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Name of the workflow."),
        sa.Column("description", sa.Text(), nullable=True, comment="Description of the workflow."),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the workflow is active or not.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the workflow was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the workflow was last updated.",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_workflows_user_id"), "workflows", ["user_id"], unique=False, schema="public"
    )
    op.create_table(
        "files",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique identifier for the file."),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="ID of the user who uploaded the file."
        ),
        sa.Column(
            "workflow_id", sa.UUID(), nullable=True, comment="Workflow ID of the file (Optional)."
        ),
        sa.Column(
            "filename",
            sa.String(length=255),
            nullable=False,
            comment="Original name of the uploaded file.",
        ),
        sa.Column(
            "s3_key",
            sa.String(length=512),
            nullable=False,
            comment="S3 storage key/path for the file.",
        ),
        sa.Column(
            "status",
            sa.Enum("UPLOADED", "EMBEDDED", "FAILED", name="filestatus"),
            nullable=False,
            comment="Current file status ex: uploaded, embedded, failed",
        ),
        sa.Column(
            "file_metadata",
            sa.JSON(),
            nullable=True,
            comment="Metadata of the file ex: { 'content_type': 'application/pdf' }",
        ),
        sa.Column(
            "processed",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the file has been processed.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the file was uploaded.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the file was last updated.",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["public.users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["public.workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_files_user_id"), "files", ["user_id"], unique=False, schema="public"
    )
    op.create_index(
        op.f("ix_public_files_workflow_id"), "files", ["workflow_id"], unique=False, schema="public"
    )
    op.create_table(
        "workflow_nodes",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the workflow node."
        ),
        sa.Column(
            "workflow_id", sa.UUID(), nullable=False, comment="Workflow this node belongs to."
        ),
        sa.Column(
            "type",
            sa.String(length=100),
            nullable=False,
            comment="Type of the node, e.g. 'UserQuery', 'KnowledgeBase', 'LLMEngine', 'Output'.",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
            comment="Optional name/label for the node.",
        ),
        sa.Column(
            "position",
            sa.JSON(),
            nullable=True,
            comment="Canvas position of the node in the frontend workspace.",
        ),
        sa.Column(
            "config",
            sa.JSON(),
            nullable=True,
            comment="Configuration options for this node (model, API keys, parameters).",
        ),
        sa.Column(
            "connections",
            sa.JSON(),
            nullable=True,
            comment="List of connections between nodes: [{'source': 'node1', 'target': 'node2', 'sourceHandle': 'output', 'targetHandle': 'input'}]",
        ),
        sa.Column(
            "execution_order",
            sa.Integer(),
            nullable=True,
            comment="Execution sequence order within the workflow.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the node was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the node was last updated.",
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["public.workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_workflow_nodes_workflow_id"),
        "workflow_nodes",
        ["workflow_id"],
        unique=False,
        schema="public",
    )
    op.create_table(
        "file_embeddings",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the file embedding."
        ),
        sa.Column("file_id", sa.UUID(), nullable=False, comment="ID of the associated file."),
        sa.Column(
            "chunk_index",
            sa.Integer(),
            nullable=False,
            comment="Index of the chunk within the document.",
        ),
        sa.Column(
            "chunk_text",
            sa.Text(),
            nullable=False,
            comment="The actual text content of this chunk.",
        ),
        sa.Column(
            "vector",
            sa.LargeBinary(),
            nullable=False,
            comment="Vector embedding data for the document chunk.",
        ),
        sa.Column(
            "embedding_metadata",
            sa.JSON(),
            nullable=True,
            comment="JSON containing additional embedding metadata.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the embedding was created.",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the embedding was last updated.",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["public.files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_file_embeddings_file_id"),
        "file_embeddings",
        ["file_id"],
        unique=False,
        schema="public",
    )
    op.alter_column(
        "user_sessions",
        "user_id",
        existing_type=sa.UUID(),
        comment="ID of the user who owns the session.",
        existing_comment="ID of the user who owns the session (optional).",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        comment="User's email address (unique).",
        existing_comment="User's email address (unique but optional).",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        comment="User's email address (unique but optional).",
        existing_comment="User's email address (unique).",
        existing_nullable=False,
    )
    op.alter_column(
        "user_sessions",
        "user_id",
        existing_type=sa.UUID(),
        comment="ID of the user who owns the session (optional).",
        existing_comment="ID of the user who owns the session.",
        existing_nullable=False,
    )
    op.drop_index(
        op.f("ix_public_file_embeddings_file_id"), table_name="file_embeddings", schema="public"
    )
    op.drop_table("file_embeddings", schema="public")
    op.drop_index(
        op.f("ix_public_workflow_nodes_workflow_id"), table_name="workflow_nodes", schema="public"
    )
    op.drop_table("workflow_nodes", schema="public")
    op.drop_index(op.f("ix_public_files_workflow_id"), table_name="files", schema="public")
    op.drop_index(op.f("ix_public_files_user_id"), table_name="files", schema="public")
    op.drop_table("files", schema="public")
    op.drop_index(op.f("ix_public_workflows_user_id"), table_name="workflows", schema="public")
    op.drop_table("workflows", schema="public")
    # ### end Alembic commands ###
