"""modified file embeddings model and relationships

Revision ID: bfa3a4d93afd
Revises: 69f53731eb20
Create Date: 2025-10-31 20:05:08.300065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfa3a4d93afd'
down_revision: Union[str, Sequence[str], None] = '69f53731eb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_embeddings', sa.Column('chroma_id', sa.String(length=100), nullable=False, comment='Unique identifier for the document chunk in ChromaDB vector store.'))
    op.create_index(op.f('ix_public_file_embeddings_chroma_id'), 'file_embeddings', ['chroma_id'], unique=False, schema='public')
    op.drop_constraint(op.f('file_embeddings_file_id_fkey'), 'file_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'file_embeddings', 'files', ['file_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('file_embeddings', 'vector')
    op.drop_constraint(op.f('files_workflow_id_fkey'), 'files', type_='foreignkey')
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'workflows', ['workflow_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'files', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('workflow_nodes_workflow_id_fkey'), 'workflow_nodes', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_nodes', 'workflows', ['workflow_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('workflows_user_id_fkey'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_user_id_fkey'), 'workflows', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'workflow_nodes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_nodes_workflow_id_fkey'), 'workflow_nodes', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'files', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('files_workflow_id_fkey'), 'files', 'workflows', ['workflow_id'], ['id'])
    op.add_column('file_embeddings', sa.Column('vector', postgresql.BYTEA(), autoincrement=False, nullable=False, comment='Vector embedding data for the document chunk.'))
    op.drop_constraint(None, 'file_embeddings', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('file_embeddings_file_id_fkey'), 'file_embeddings', 'files', ['file_id'], ['id'])
    op.drop_index(op.f('ix_public_file_embeddings_chroma_id'), table_name='file_embeddings', schema='public')
    op.drop_column('file_embeddings', 'chroma_id')
    # ### end Alembic commands ###
